export { default as Text } from './Text'
export { default as Button } from './Button'
export { default as Icon } from './Icon'
export { default as Title } from './Title'
export { default as Image } from './Image'
export { default as InputText } from './InputText'
export { default as Label } from './Label'